// Generated by delombok at Fri Feb 14 16:32:02 GMT 2014
package org.goochjs.jskills.factorgraphs;

public class KeyedVariable<TKey, TValue> extends Variable<TValue> {
	private final TKey key;
	
	public KeyedVariable(TKey key, TValue prior, String name, Object... args) {
		super(prior, name, args);
		this.key = key;
	}
	
	@java.lang.SuppressWarnings("all")
	public TKey getKey() {
		return this.key;
	}
}